### ISSUE TITLE
[StarLite Mk V] Missing features but stated on the Star Lite product page

### ISSUE THREAD

**Issue by meeuw** [StarLabsLtd/firmware#205]
I kind of expected the StarLite Mk V to have support of what's listed on the product page:

https://starlabs.systems/pages/starlite
![CFR-01x2000](https://github.com/user-attachments/assets/39dc8cc1-763d-457e-b645-032f4ba2d440)

I don't see any options for enabling Secure Boot, Fn Ctrl Reverse, Thunderbolt, Legacy 8254 Timer

**Comment by Sean-StarLabs** [comment]
We use the same image for all of our models because the options will always been in a state of flux. No OS requires the legacy timer anymore, so it's now essentially "Do you want to waste power and inhibit performance?". Equally, the option for Thunderbolt will only show on platforms that have Thunderbolt it, as all enabling it on a platform that doesn't have it will do is waste power.

Feel free to log feature requests if you want to see an option.
