### ISSUE TITLE
Alert on UEFI dbx lite mkIII

### ISSUE THREAD

**Issue by soc7** [StarLabsLtd/firmware#219]
I am seeing an alert after updating the UEFI dbx  to version 190 on the lite mkIII as following:

UEFI Secure Boot Forbidden Signature Database

This updates the dbx to the latest release from Microsoft which adds insecure versions of grub and shim to the list of forbidden signatures due to multiple discovered security updates.

And it poits those CVEs as issues:
CVE-2020-7205
CVE-2020-15707
CVE-2020-15706
CVE-2020-15705
CVE-2020-14311
CVE-2020-14310
CVE-2020-14309
174059
CVE-2020-14308
CVE-2020-10713

Should I be worried?

**Comment by Sean-StarLabs** [comment]
> Should I be worried?

What are you asking?

**Comment by soc7** [comment]
How serious are those vulnerabilities?

**Comment by Sean-StarLabs** [comment]
Real-world, likely not very.  Severity scores are more of a "what could happen".

**Comment by soc7** [comment]
Like only physical attack? No remote attack?

**Comment by Sean-StarLabs** [comment]
I don't know - most require some level of access to exist before they're an issue

**Comment by samueldr** [comment]
> Should I be worried? [about UEFI dbx updates]

Those updates only affect use of Secure Boot. They “revoke” [actually deny-list] public keys from being allowed for use with Secure Boot enabled.

 - They do not change the UEFI for your system
 - They do not fix bugs in the UEFI for your system
 - They prevent vulnerable (buggy) ***Secure Boot signed binaries*** from running when Secure Boot is enabled.

* * *

Since your initial message doesn't clearly state whether ***you*** are using Secure Boot, it depends:

First of all, like Sean said, they all pretty much require some form of access to the system (physical access, or other vulnerabilities to exploit) so boot entries can be modified, or added.

**If you are using Secure Boot, *and* rely on Secure Boot for its properties**: maybe, you could be worried. Not updating the revocation list means known insecure signed binaries can still run on your system at the bootloader stage.

**If you are not using Secure Boot (e.g. by disabling it)**: no, because whether signed or not, any arbitrary binaries can already be booted on your system.
